development: &MYSQL_DB
  adapter: mysql
  username: root
  password: 
  encoding: utf8
  host: localhost
  database: tiny_mon_production

production:
  <<: *MYSQL_DB

test: &TEST
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

cucumber:
  <<: *TEST
