development:
  adapter: mysql
  username: root
  password:
  encoding: utf8
  host: localhost
  database: tiny_mon_development

test: &TEST
  adapter: mysql
  username: root
  password:
  encoding: utf8
  host: localhost
  database: tiny_mon_test

cucumber:
  <<: *TEST
